server:
  port: 8080

eureka:  
  client:    
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
spring:
  datasource:
    url: jdbc:mysql://root:CkoLykFANsdUJHukhfhoOexQCvkMJkMi@roundhouse.proxy.rlwy.net:54140/railway
    username: root
    password: CkoLykFANsdUJHukhfhoOexQCvkMJkMi
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: business-service
          uri: lb://business-service
          predicates:
            - Path=/api/v1/**
        - id: users-service
          uri: lb://users-service
          predicates:
            - Path=/api/v1/**
